export const BASE_URL = 'https://api.com/'
export const OTP_BASE_URL = 'https://graph.facebook.com/v21.0/547561908437857/messages'
export const ACCESS_TOKEN_OTP = 'EAAJRZBeBoBmEBOxG4ScnNmG8lPVvHtHHxzFTR5Ym5fQdYXEZCb9Kh74F0ZCCiq04xRxYDGFjKMo8e2lZA4G3zcvDWcWQwRQqdUQr1Gact1RbDT1lOtIgtTU2GvOy8NuT6IcZCtfZAYFD0P2K9sam8qn9QTH76Uh2xKsk6owngox5xF78cHQv9tt4Ot8lOCIUUh'
export const ACCESS_TOKEN = 'EAAJRZBeBoBmEBO90conlwTqxFe4FpuGNVaYPuyyR6qeRAdWTZCK31GFfySTKzpM3c9CZAWui89UuQ9B39A9xKc7Gh5AHmWqXaXURQFiw5KWAnMQv6uFZBf1wbfqLMhUnzpAkHCuMTmZAwHklfHLghiS4ESXykBxd8rdjvfas5qcm9nqFBmZCJidy97gfT4ZCz8u'
export const PHONE_ID = '547561908437857'

export const ACTION_TYPES={
    LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
    LOGOUT_SUCCEEDED: 'LOGOUT_SUCCEEDED',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
    STAGES_UPDATE: 'STAGES_UPDATE',

    CURRENT_SCREEN: 'CURRENT_SCREEN',

    OTP_REQUESTED: 'OTP_REQUESTED',
    OTP_SUCCESS: 'OTP_SUCCESS',
    OTP_FAILED: 'OTP_FAILED',

}